-- Удаление всех объектов и файлов
DROP ALL OBJECTS DELETE FILES;

-- Таблица пользователей Filmorate
CREATE TABLE IF NOT EXISTS User_Filmorate (
    user_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR,
    login     VARCHAR,
    name_user VARCHAR,
    birthday  DATE
);

-- Таблица возрастных рейтингов MPA
CREATE TABLE IF NOT EXISTS Mpa (
    mpa_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name    VARCHAR
);

-- Таблица жанров фильмов
CREATE TABLE IF NOT EXISTS Genre (
    genre_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name   VARCHAR
);

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS Film (
    film_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name     VARCHAR,
    description   VARCHAR,
    release_date  DATE,
    duration      INTEGER,
    rate          INTEGER,
    mpa_id        INTEGER,
    FOREIGN KEY (mpa_id) REFERENCES Mpa(mpa_id) ON DELETE CASCADE
);

-- Таблица связей между жанрами и фильмами
CREATE TABLE IF NOT EXISTS Genre_Film (
    genre_film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id       INTEGER,
    FOREIGN KEY (film_id) REFERENCES Film(film_id) ON DELETE CASCADE,
    genre_id      INTEGER,
    FOREIGN KEY (genre_id) REFERENCES Genre(genre_id) ON DELETE CASCADE
);

-- Таблица лайков фильмов от пользователей
CREATE TABLE IF NOT EXISTS Like_Film (
    like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER,
    FOREIGN KEY (film_id) REFERENCES Film(film_id) ON DELETE CASCADE,
    user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES User_Filmorate(user_id) ON DELETE CASCADE
);

-- Таблица дружбы между пользователями
CREATE TABLE IF NOT EXISTS Friendship (
    friendship_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    friend_id     INTEGER,
    FOREIGN KEY (friend_id) REFERENCES User_Filmorate(user_id) ON DELETE CASCADE,
    user_id       INTEGER,
    FOREIGN KEY (user_id) REFERENCES User_Filmorate(user_id) ON DELETE CASCADE
);